version: '2'
services:
  consul:
    container_name: consul
    image: consul:1.0.0

    command: "consul agent -server -client 0.0.0.0 -bootstrap -data-dir=/consul/data -ui"

    ports:
      - 8500:8500

  shelf2-backend:
    container_name: shelf2
    image: quay.io/sirech/shelf2-backend

    ports:
      - 3000:3000

    command: "envconsul -consul-addr consul:8500 -prefix shelf2-backend -upcase rails s -b 0.0.0.0"

    depends_on:
      - consul
