version: '2'
services:
  nginx:
    container_name: nginx
    build: ./nginx

    env_file: .env

    environment:
      SHELF2_HOST: "shelf2.${HOST}"
    
    ports:
      - "80:80"

    volumes:
      - "/srv/main:/srv/main:ro"
      - "/srv/images:/srv/images:ro"
      - "shelf2_public:/srv/shelf2_public:ro"

    depends_on:
      - shelf2
      - homepage

    command: ./run.sh

  db:
    container_name: db
    image: mysql:5.6

    env_file: .env

    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

    ports:
      - 3306:3306

    volumes:
      - db:/var/lib/mysql

  shelf2:
    container_name: shelf2
    build: ./shelf2

    env_file: .env

    environment:
      DB_HOST: db
      RAILS_LOG_TO_STDOUT: 1

    ports:
      - 3000:3000

    volumes:
      - shelf2_public:/app/public

    depends_on:
      - db

  homepage:
    container_name: homepage
    build: ./homepage

    env_file: .env

    volumes:
      - "/srv/main:/app/public"

volumes:
  db:
  shelf2_public:
