version: '2'
services:
  nginx:
    container_name: nginx
    build: ./nginx

    env_file: .env

    environment:
      SHELF_HOST: "shelf.${HOST}"
    
    ports:
      - "80:80"

    volumes:
      - "public:/srv/public:ro"

    depends_on:
      - shelf

    command: /bin/bash -c "envsubst \$$SHELF_HOST < /tmp/shelf.conf.template > /etc/nginx/sites-enabled/shelf.conf && nginx -g 'daemon off;'"


  db:
    container_name: db
    image: mysql:5.6

    env_file: .env

    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

    ports:
      - 3306:3306

    volumes:
      - db:/var/lib/mysql

  shelf:
    container_name: shelf
    build: ./shelf

    env_file: .env

    environment:
      DB_HOST: db
      RAILS_LOG_TO_STDOUT: 1

    ports:
      - 3000:3000

    volumes:
      - public:/app/public

    depends_on:
      - db

volumes:
  db:
  public:

